"""Initial migration

Revision ID: 78158a1ce716
Revises: d8f3a672a7ea
Create Date: 2026-09-04 20:11:35.983275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78158a1ce716'
down_revision: Union[str, Sequence[str], None] = 'd8f3a672a7ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('places',
    sa.Column('uuid', sa.UUID(), nullable=False, comment='Уникальный идентификатор площадки'),
    sa.Column('name', sa.String(), nullable=False, comment='Название площадки'),
    sa.Column('city', sa.String(), nullable=False, comment='Город'),
    sa.Column('address', sa.String(), nullable=False, comment='Адрес'),
    sa.Column('seats_pattern', sa.String(), nullable=False, comment='паттерн мест в формате A1-1000,B1-2000'),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Дата и время последнего изменения площадки'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Дата и время создания площадки'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('events',
    sa.Column('uuid', sa.UUID(), nullable=False, comment='Уникальный идентификатор события'),
    sa.Column('place_id', sa.UUID(), nullable=False, comment='Площадка, где будет проходить событие'),
    sa.Column('name', sa.String(), nullable=False, comment='Название мероприятия'),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False, comment='Дата и время начала мероприятия'),
    sa.Column('registration_deadline', sa.DateTime(timezone=True), nullable=False, comment='крайний срок регистрации'),
    sa.Column('status', sa.String(), nullable=True, comment='Статус события'),
    sa.Column('number_of_visitors', sa.Integer(), nullable=False, comment='Количество зарегистрированных участников'),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Дата и время последнего изменения'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Дата и время создания'),
    sa.Column('status_changed_at', sa.DateTime(timezone=True), nullable=True, comment='Дата и время последнего изменения статуса'),
    sa.ForeignKeyConstraint(['place_id'], ['places.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_events_place_id'), 'events', ['place_id'], unique=False)
    op.create_table('seats',
    sa.Column('id', sa.Integer(), nullable=False, comment='Уникальный идентификатор места'),
    sa.Column('place_id', sa.UUID(), nullable=False, comment='Площадка, где будет проходить событие'),
    sa.Column('section', sa.String(length=1), nullable=False, comment='Секция'),
    sa.Column('seat_number', sa.Integer(), nullable=False, comment='Номер места'),
    sa.Column('is_available', sa.Boolean(), nullable=True, comment='Статус места'),
    sa.ForeignKeyConstraint(['place_id'], ['places.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registrations',
    sa.Column('uuid', sa.UUID(), nullable=False, comment='Уникальный идентификатор регистрации'),
    sa.Column('first_name', sa.String(), nullable=False, comment='Имя'),
    sa.Column('last_name', sa.String(), nullable=False, comment='Фамилия'),
    sa.Column('event_id', sa.UUID(), nullable=False, comment='Идентификатор мероприятия'),
    sa.Column('seat_id', sa.Integer(), nullable=False, comment='Идентификатор места'),
    sa.Column('email', sa.String(), nullable=False, comment='Почта'),
    sa.Column('ticket_id', sa.UUID(), nullable=True, comment='Уникальный идентификатор билета'),
    sa.ForeignKeyConstraint(['event_id'], ['events.uuid'], ),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registrations')
    op.drop_table('seats')
    op.drop_index(op.f('ix_events_place_id'), table_name='events')
    op.drop_table('events')
    op.drop_table('places')
    # ### end Alembic commands ###
